{
 "title": "Logging",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  { "title": "Service: API", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "<= 399",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "count(rate({service=\"api\"} | json | status <= 399 [$__auto]))"
    }
   ]
  },
  {
   "title": "400 - 499",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "count(rate({service=\"api\"} | json | status >= 400 and status <= 499 [$__auto]))"
    }
   ]
  },
  {
   "title": "400 - 499",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "count(rate({service=\"api\"} | json | status >= 500 [$__auto]))"
    }
   ]
  },
  {
   "title": "Logs",
   "type": "logs",
   "gridPos": { "h": 17, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "{service=\"api\"} | json"
    }
   ]
  }
 ]
}